### ISSUE TITLE
suggestion: use md instead of Rmd for file extensions. 

### ISSUE THREAD

**Issue by zkamvar** [carpentries-incubator/scientific-metadata#14]
I noticed that you are using files with the `Rmd` extension, but there doesn't appear to be any R code embedded. The lesson will build faster if you change the extensions of your episodes to be `md`.

**Comment by SilkeGerlich** [comment]
Hi @zkamvar,
thank you very much for the suggestion! I changed the `Rmd` files to `md`. :muscle:
