### ISSUE TITLE
[Content Review] Instructor perspective

### ISSUE THREAD

**Issue by SilkeGerlich** [carpentries-incubator/scientific-metadata#2]
<i>This content review will be conducted through the eyes of a potential instructor. It focuses on the content that is directed specifically at instructors (anything <u>only</u> accessible in instructor view mode).</i>

### General review instructions

<u>**Where to start**</u>
- Browse the website that I have shared with you (<i>Start here:</i> `site/docs/index.html`) in **Instructor View**.
- Open the document's diff in the pull request #1  (from the list of documents provided below), that corresponds with the site you are currently reviewing, in Githubs WebIDE.

<u>**Minor Changes**</u>
If you find a typo or grammar mistakes, feel free to directly change them in the individual documents provided below.

<u>**Major Changes**</u>
If you find larger issues with the content (representation, structure, clarity), **comment** preferably at the respective place in the pull request. Or use this issue for overarching comments or feature requests

<u>**While reviewing the content**</u>
please also keep an eye on:
- spelling / grammar
- hyperlinks (all links should be active and open a new tab in your browser.)
- general clarity / understandability
- site navigation

### Through the eyes of an INSTRUCTOR :eyes: 

<u>**Guiding questions**</u>

<i>Keep these questions in the back of your mind, while reviewing the content</i>

- Are the learner profiles (`Learner view`) clear and do they give you a good idea of the target group?
- Are the instructions clear and understandable? Do you lack further information?
- Is it easy to navigate the lesson and find the information you are looking for?
- Is the attached material complete, comprehensive and findable?
- Do you feel comfortable to hold this lesson based on the given information? 

<u>**Focus points**</u>
- instructor notes (pink boxes)
- slide set and talking points
- schedule
- navigation

### List of documents for review

**look at these documents <u>in depth**</u>:
1. Landing page: [index.md](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5)
2. General Lesson Information: [general-lesson-information.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-81d551aaca7e0003d8d23aefa989a911a666e3c6bf0ccd465d56d72e6fdf7c97) (<i>metadata on top will be updated during the review</i> :wink:)
3. Instructor Guide: [instructor-guide.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-190683f22b50e27b388a4b8d793da1bdfe7374ab7430e00eb98ac082280308dd)

**instructor content in these document is duplicated from `instructor-guide.Rmd`. <u>Scan</u> these documents / sites for consistency:**
1. Episode 1: [getting-started.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-446ce2132bcd9967bdb9220702a95d7481b7e68e59f60a41312c1441f6ccec2b)
2. Episode 2: [data-metadata.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-66f9901b2d17f584be2626216049faa9f5cb1a2e96130f1b1156ebfff10e3ab2)
3. Episode 3: [structure-schema.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-4dca653c0fc4d8be7713a8da53b5f27189ba07b380ffef7a1deb5abe0d044ea2)
4. Episode 4: [enabling-technologies-standards.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-b7615f6a915828c63fb66158b243ff2a67af8fbb2acf90aaf5136623d95dea97)
5. Episode 5: [web-locations-identifiers.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-91be0603ae8b1b4812c366213c17b08e770e9acdbf2f2768554444d8cd4657fd)

**<u>disregard these files</u> as they are still under construction:**
1. Acknowledgements: acknowledgements.Rmd
2. Meet the Creators: meet-the-creators.Rmd
3. Outlook - Linked Data: conclusion-outlook.Rmd <i>will be included in lesson version 1.1</i>

### When you finish your review
- Head over to the [pull request](https://github.com/carpentries-incubator/scientific-metadata/pull/1)
- Check your tick box in the first comment
- Comment yourself, if you like :wink:

### Good to know

If you have immediate questions or need a quick fix, use the review Mattermost channel or comment in this issue.

**:heart: Thank you so much for your support in the reviewing process :heart:**

**Comment by aazocar** [comment]
Guiding questions
- Are the learner profiles (Learner view) clear and do they give you a good idea of the target group?

1. Yes, learner profiles are great 👍🏽 
2. In the learner view, you land in Summary and Setup, what is the Setup part referring to?

- Are the instructions clear and understandable? Do you lack further information?

1. In general I felt it was all clear. When we reached the last lecture about the web and so on, I wondered if it's clear to all learners. 🤔 
2. In these two cases, Challenge: Metadata Standards and Guided Confrontation: Metadata in Scientific Publications. I did wonder if someone who has not seen it before would be able to get what to do. Maybe some warning that you should know some metadata standards in some scientific fields? Or maybe you can give some examples. In the publication case, I asked if the penguin poop will be suggested, if not, there should be at least some sort of warning that it should be a very short publication.

- Is it easy to navigate the lesson and find the information you are looking for?
- Is the attached material complete, comprehensive and findable?

1. In the Summary and Schedule section I completely missed the schedule 😁 It comes after the HMC logo and I thought this comes at the end. 
2. Also, depending where you are, the pages on top change, for me it would be better if you could always have the General lesson information and the Instructor guide on top (most of the time they come under more...) 

- Do you feel comfortable to hold this lesson based on the given information?

1. Is there a meaning to bold face in the lecture talking points. Sometimes it was important words (like HTTP or GET), sometimes it was the most important point of the slide. I guess one could streamline this, but it's not super important.

**Comment by aazocar** [comment]
I don't know if this is relevant but in [JsonStepByStep.pdf](https://github.com/carpentries-incubator/scientific-metadata/files/slideSet/JsonStepByStep_CarpentriesIncubator_ScientificMetadata.pdf), the example is using double comma quotation marks (the curly ones). If you copy paste this into a JSON formatter it complains that it is invalid, and you have to use the Fix JSON option, where it replaces the incorrect quotes.  Would it be better to replace the quotations directly on the slides?

same in slides 5-7 of MetadataSchemas slides

**Comment by apirogov** [comment]
Yeah, in technical stuff you should use `'` and `"`, everything else usually will be broken and not work. For prose and actual quotes, ideally use the special correct symbols.

**Comment by aazocar** [comment]
In the TODO: Before the lesson

> send the link to the “Episode 1: Getting started” 2-3 days before the lesson starts.

Is it possible to send the link only to one episode? or would people get access to the full lesson?
