### ISSUE TITLE
[Content Review] Carpentries perspective

### ISSUE THREAD

**Issue by SilkeGerlich** [carpentries-incubator/scientific-metadata#3]
<i>This content review will be conducted through the eyes of the Carpentries. It regards the lesson and instructions in general</i>

### General review instructions

<u>**Where to start**</u>
- Browse the website that I have shared with you (<i>Start here:</i> `site/docs/index.html`) in **Instructor View**.
- Open the document's diffs of the pull request #1  (see list provided below), that corresponds with the site you are currently reviewing, in Githubs WebIDE.

<u>**Minor Changes**</u>
If you find a typo or grammar mistakes, feel free to directly change them in the individual documents provided below.

<u>**Major Changes**</u>
If you find larger issues with the content (representation, structure, clarity), **comment** preferably at the respective place in the pull request. Or use this issue for overarching comments or feature requests

<u>**While reviewing the content**</u>
please also keep an eye on:
- spelling / grammar
- hyperlinks (all links should be active and open a new tab in your browser.)
- clarity / understandability
- site navigation

### Through the eyes of an INSTRUCTOR :eyes: 

<u>**Guiding questions**</u>

<i>Keep these questions in the back of your mind, while reviewing the content</i>

- Does the content comply with the overall Carpentries philosophy?
- - Does the lecture comply with the Carpentries guidelines for instructors and content representation?
- Is the lesson structure coherent, complete and comprehensive?
- Is the lesson content coherent, complete and comprehensive?
- Is the attached material complete, comprehensive and findable?
- As a Carpentries instructor, would you feel comfortable to give this lesson and / or include it in your curriculum?

<u>**Focus points**</u>
- lesson structure (silver lining)
- episode integrity
- integrity of instructor and learner content

### List of documents for review

**look at these documents <u>in depth**</u>:
1. Landing page: [index.md](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5)
2. Learner profiles: [learner-profiles.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-8c5348470e31be644bd8821d243f73941571b7ddcd81539e11eba340355028ca)
3. General Lesson Information: [general-lesson-information.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-81d551aaca7e0003d8d23aefa989a911a666e3c6bf0ccd465d56d72e6fdf7c97) (<i>metadata on top will be updated during the review</i> :wink:)
4. Instructor Guide: [instructor-guide.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-190683f22b50e27b388a4b8d793da1bdfe7374ab7430e00eb98ac082280308dd)
5. Episode 1: [getting-started.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-446ce2132bcd9967bdb9220702a95d7481b7e68e59f60a41312c1441f6ccec2b)
6. Episode 2: [data-metadata.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-66f9901b2d17f584be2626216049faa9f5cb1a2e96130f1b1156ebfff10e3ab2)
7. Episode 3: [structure-schema.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-4dca653c0fc4d8be7713a8da53b5f27189ba07b380ffef7a1deb5abe0d044ea2)
8. Episode 4: [enabling-technologies-standards.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-b7615f6a915828c63fb66158b243ff2a67af8fbb2acf90aaf5136623d95dea97)
9. Episode 5: [web-locations-identifiers.Rmd](https://github.com/carpentries-incubator/scientific-metadata/pull/1/files#diff-91be0603ae8b1b4812c366213c17b08e770e9acdbf2f2768554444d8cd4657fd)

**<u>disregard these files</u> as they are still under construction:**
1. Acknowledgements: acknowledgements.Rmd
2. Meet the Creators: meet-the-creators.Rmd
3. Outlook - Linked Data: conclusion-outlook.Rmd <i>will be included in lesson version 1.1</i>

### When you finish your review
- Head over to the [pull request](https://github.com/carpentries-incubator/scientific-metadata/pull/1)
- Check your tick box in the first comment
- Comment yourself, if you like :wink:

### Good to know

If you have immediate questions or need a quick fix, use the review Mattermost channel or comment in this issue.

**:heart: Thank your so much for you support in the reviewing process :heart:**

**Comment by apirogov** [comment]
High-level checks against the [Curriculum Development Handbook](https://cdh.carpentries.org/)

- [X] clearly follows the Backward design principle / building course with target learning objectives in mind
- [X] uses elements of [live coding](https://cdh.carpentries.org/developing-content.html#code-chunks) and "didactic thinking aloud"
- [X] clearly defined [target audience](https://cdh.carpentries.org/deciding-what-to-teach.html#target-audience), [learning objectives and key points](https://cdh.carpentries.org/developing-content.html#supporting-elements)
- [X] extensive [instructor material](https://cdh.carpentries.org/developing-content.html#narrative-text)

- [ ] not domain-specific / immediately relatable to scientists daily work
*but possible spin-offs could fit the content into various domain contexts*

- [ ] Challenges are somewhat more complex than "typical" carpentries challenge (e.g. filling in blanks / multiple choice)
*but group-work based approach makes it more approachable. The provided challenges clearly try to put theory into practice i.e. [putting it into a (different) context](https://cdh.carpentries.org/designing-challenges.html#use-the-concept-in-a-different-context)*

**Comment by apirogov** [comment]
There is a wrongly rendered hyperlink in for `Data & Metadata`: (the `&amp;`), probably its a problem in the pipeline:

![2023-03-07-122719_782x330_scrot](https://user-images.githubusercontent.com/371708/223409417-575e75ee-c871-4043-8029-537d9a117bd4.png)
![2023-03-07-122659_756x199_scrot](https://user-images.githubusercontent.com/371708/223409421-8e92edb0-bba2-4635-be94-6ec0a78c2621.png)

**Comment by apirogov** [comment]
What is the difference between "data object" and "dataset" in the scope of the lesson?

The "example data object" is just a "dataset" with bad metadata, isn't it?

**Comment by apirogov** [comment]
Is the "instructor guide" using actually duplicated snippets from the other resources?

Ideally, this could embed from the other files.

**Comment by apirogov** [comment]
Some files are duplicated. Is this for technical reasons?

**Comment by SilkeGerlich** [comment]
> What is the difference between "data object" and "dataset" in the scope of the lesson?
> 
> The "example data object" is just a "dataset" with bad metadata, isn't it?



Can you specify this question? If it is regarding the "example data object", then the "data set" does not apply (anymore). We've change the terminology to data object because dataset and data object can not be used interchangeably -> data set > 1 file.
In connection with the example data object "dataset" would be an artifact, which I will have to get rid off. Please mark this in the  `.Rmd`s

**Comment by SilkeGerlich** [comment]
> Is the "instructor guide" using actually duplicated snippets from the other resources?
> 
> Ideally, this could embed from the other files.

Good point! Yes, they are actual duplicates. Will try if this works with the pipeline (not sure, if the rendering works :) )

**Comment by apirogov** [comment]
Learner view: link to glossary is broken (if there is no glossary, remove? otherwise fix?)

**Comment by SilkeGerlich** [comment]
> There is a wrongly rendered hyperlink in for `Data & Metadata`: (the `&amp;`), probably its a problem in the pipeline:
> 

Tried to fix it with different approaches but failed. Probably something in the pandoc pipeline. Will be included in the Workbench Beta-Test Feedback.

**Comment by apirogov** [comment]
> > What is the difference between "data object" and "dataset" in the scope of the lesson?
> > The "example data object" is just a "dataset" with bad metadata, isn't it?
> 
> Can you specify this question? If it is regarding the "example data object", then the "data set" does not apply (anymore). We've change the terminology to data object because dataset and data object can not be used interchangeably -> data set > 1 file. In connection with the example data object "dataset" would be an artifact, which I will have to get rid off. Please mark this in the `.Rmd`s

I disagree about dataset = > 1 file, see e.g. https://en.wikipedia.org/wiki/Data_set or https://www.oxfordlearnersdictionaries.com/definition/american_english/data-set

It says nothing about files, and in fact a single file with multiple pieces of information in my eyes qualifies as "dataset", i.e. a CSV file is a dataset

In any case one can argue if you have *one* JSON object of the same kind in a file, its not really a "dataset", so I see your point.

btw, I "fixed" all `data set` to `dataset` (did not know the other spelling is ok + carpentries always write dataset as one word)

**Comment by apirogov** [comment]
> > There is a wrongly rendered hyperlink in for `Data & Metadata`: (the `&amp;`), probably its a problem in the pipeline:
> 
> Tried to fix it with different approaches but failed. Probably something in the pandoc pipeline. Will be included in the Workbench Beta-Test Feedback.

In the PR I suggested, you could also simply substitute `&` into `and` as a workaround (unless you have a strong preference)

**Comment by hofmannv** [comment]
i agree: a data set is not characterised by the number of files it is saved at. It is consists of multiple pieces of data (in one or multiple files) that are grouped according to some characteristic.

from HDO: 
definition "A generically dependent continuant which is composed always of multiple datum instances, which are grouped intentionally according to one or more common characteristics."@en
rdfs:comment "Intention may be related to analysis, storage or publication of that data(set). For example, all files that are stored together on one CD-ROM or DVD might constitute a dataset as they are stored physically together. The organisation of the collection might strongly differ between application cases."@en

However i don't see a problem with calling the example data either `example data`, `example data set` or `example data object` (while the last one sounds like there is something more formal to it...).
